"""empty message

Revision ID: 4820eeee45c5
Revises: 89186b3dfcca
Create Date: 2021-11-07 10:53:55.018509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4820eeee45c5'
down_revision = '89186b3dfcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('restaurants_email_key', 'restaurants', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('restaurants_email_key', 'restaurants', ['email'])
    # ### end Alembic commands ###
